apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-killer-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-killer-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-killer-binding
subjects:
  - kind: ServiceAccount
    name: pod-killer-sa
roleRef:
  kind: Role
  name: pod-killer-role
---
apiGroup: rbac.authorization.k8s.io
apiVersion: batch/v1
kind: CronJob
metadata:
  name: kill-pod
spec:
  schedule: "0 */8 * * *"  # every 8 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: killer
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - kubectl delete pod -l app=bank-app -n bank-app
          restartPolicy: OnFailure
          serviceAccountName: pod-killer-sa
