apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bank-app
  name: bank-app
spec:
  replicas: 1
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app: bank-app
  template:
    metadata:
      labels:
        app: bank-app
    spec:
      containers:
        - name: bank-app
          env:
            - name: LOG_LEVEL
              value: INFO
            - name: PORT
              value: "8080"
          image: codeberg.org/marcusjy/bank-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          # readinessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 3
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          # livenessProbe:
          #   httpGet:
          #     path: /healthz
          #     port: 8080
          #   initialDelaySeconds: 10
          #   periodSeconds: 5
          #   timeoutSeconds: 5
          #   failureThreshold: 3
          resources:
            requests:
              cpu: 10m
              memory: 25Mi
            limits:
              cpu: 20m
              memory: 50Mi
      restartPolicy: Always
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
