openapi: 3.1.0
info:
  title: Treasury Yield API
  description: API for managing treasury yield orders and data
  version: 1.0.0

servers:
  - url: http://localhost:8080/
    description: Local Development Server
  - url: https://bank-app.yanello.net/
    description: Production Server

paths:
  /api/v1/orders:
    get:
      summary: Get list of treasury yield orders
      tags:
        - Orders
      responses:
        "200":
          description: Order list retrieved successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Orders"
  /api/v1/order:
    post:
      summary: Submits an order for treasury yields
      tags:
        - Orders
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      responses:
        "200":
          description: Order request submitted successfully
          content: {}

  /healthz:
    get:
      summary: Health Check
      description: Returns the health status of the service
      tags:
        - System
      responses:
        "200":
          description: Service is healthy
          content:
            text/html:
              schema:
                type: string
              example: "OK"

components:
  schemas:
    Order:
      type: object
      required:
        - term
        - amount
      properties:
        term:
          type: integer
          example: 10
          description: Term in months
        amount:
          type: number
          format: float
          example: "250000.00"
          description: Order amount in USD
    Orders:
      type: object
      required:
        - orders
      properties:
        orders:
          type: array
          items:
            $ref: "#/components/schemas/Order"
tags:
  - name: Orders
    description: General endpoints for treasury yield order management

externalDocs:
  description: Repo README
  url: https://codeberg.org/marcusjy/bank-app/src/branch/main/README.md
